version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sys
      POSTGRES_PASSWORD: sys
      POSTGRES_DB: sys
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: